Add an extra pip update on Windows
Seems like Windows runners needs to run python.exe rather than pip
directly when updating pip itself for whatever reason, otherwise the
step fails with an error like

ERROR: To modify pip, please run the following command:
C:\hostedtoolcache\windows\Python\3.11.7\x64\python.exe -m pip install
	-U pip wheel

If any new pip version is available.

Add an extra command to update pip just for Windows, leave the
subsequent one in all the time for simplicity.

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>